# Pembersihan dan Prapemrosesan data

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn_pandas import CategoricalImputer

In [4]:
df = pd.read_csv("top50contry.csv", encoding="ISO-8859-1")

df

,Unnamed: 0,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,country
0,1,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,world
1,2,ROXANNE,Arizona Zervas,pop rap,2019,1969-12-31,117.0,60.0,62.0,-6.0,46.0,46.0,164,5.0,15.0,99,world
2,3,Memories,Maroon 5,pop,2019,1969-12-31,91.0,32.0,76.0,-7.0,8.0,57.0,189,84.0,5.0,99,world
3,4,Circles,Post Malone,dfw rap,2019,1969-12-31,120.0,76.0,70.0,-3.0,9.0,55.0,215,19.0,4.0,99,world
4,5,All I Want for Christmas Is You,Mariah Carey,dance pop,1994,1969-12-31,150.0,63.0,34.0,-7.0,7.0,35.0,241,16.0,4.0,98,world
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Feelings,Lauv,pop,2019,1969-12-31,103.0,47.0,69.0,-7.0,10.0,25.0,190,9.0,4.0,73,malasya
996,997,Mimpi (feat. Alif),K-Clique,malaysian indie,2019,1969-12-31,150.0,73.0,83.0,-7.0,10.0,87.0,253,53.0,29.0,66,malasya
997,998,Cinta Luar Biasa,Andmesh,indonesian pop,2019,1969-12-31,136.0,23.0,58.0,-12.0,10.0,32.0,256,81.0,3.0,66,malasya
998,999,Haa Tepok,MeerFly,malaysian hip hop,2019,1969-12-31,87.0,50.0,85.0,-12.0,15.0,68.0,211,66.0,31.0,65,malasya
999,1000,Hanya Rindu,Andmesh,indonesian pop,2019,1969-12-31,179.0,16.0,28.0,-12.0,11.0,20.0,252,89.0,3.0,65,malasya

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1000 non-null   int64
 1   title       1000 non-null   object
 2   artist      1000 non-null   object
 3   top genre   985 non-null    object
 4   year        1000 non-null   int64
 5   added       1000 non-null   object
 6   bpm         999 non-null    float64
 7   nrgy        999 non-null    float64
 8   dnce        999 non-null    float64
 9   dB          999 non-null    float64
 10  live        999 non-null    float64
 11  val         999 non-null    float64
 12  dur         1000 non-null   int64
 13  acous       999 non-null    float64
 14  spch        999 non-null    float64
 15  pop         1000 non-null   int64
 16  country     1000 non-null   object
dtypes: float64(8), int64(4), object(5)
memory usage: 132.9+ KB

In [6]:
df.describe()

,Unnamed: 0,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
count,1000.000000,1000.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,1000.000000,999.000000,999.000000,1000.000000
mean,500.500000,2010.025000,123.644645,61.650651,64.282282,-6.807808,20.003003,59.732733,206.074000,34.894895,8.703704,81.443000
std,288.819436,16.904264,31.005120,19.064732,16.032857,3.241313,17.956443,22.000356,51.224198,28.778784,8.432230,13.090229
min,1.000000,1942.000000,47.000000,10.000000,16.000000,-23.000000,2.000000,5.000000,85.000000,0.000000,2.000000,0.000000
25%,250.750000,2011.000000,98.000000,49.000000,53.000000,-8.000000,9.000000,42.000000,172.000000,10.000000,4.000000,75.000000
50%,500.500000,2019.000000,120.000000,65.000000,67.000000,-6.000000,12.000000,61.000000,201.000000,27.000000,5.000000,85.000000
75%,750.250000,2019.000000,147.000000,76.000000,76.000000,-5.000000,25.000000,77.000000,231.000000,59.000000,9.000000,90.000000
max,1000.000000,2019.000000,205.000000,98.000000,95.000000,0.000000,98.000000,98.000000,464.000000,99.000000,56.000000,100.000000

## NORMALISASI NAMA KOLOM

Dari dataframe yang ditampilkan di atas, kita memiliki satu kolom yang paling awal (paling kiri) yang tidak bernama (unnamed), kolom yang tidak bernama ini akan menyulitkan proses analisis data. Maka, ada dua alternatif solusi:

1. Menghapus (drop) kolom tersebut
2. Memberikan nama pada kolom tersebut

Dalam dataset, terlihat bahwa konteks untuk kolom pertama tersebut adalah ID dari lagunya. Maka, untuk sementara, kolom tersebut bisa diberi nama "ID"

In [7]:
df.columns.tolist()

['Unnamed: 0',
 'title',
 'artist',
 'top genre',
 'year',
 'added',
 'bpm',
 'nrgy',
 'dnce',
 'dB',
 'live',
 'val',
 'dur',
 'acous',
 'spch',
 'pop',
 'country']

In [8]:
df.rename(columns = {"Unnamed: 0" : "ID"}, inplace=True)
df

,ID,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,country
0,1,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,world
1,2,ROXANNE,Arizona Zervas,pop rap,2019,1969-12-31,117.0,60.0,62.0,-6.0,46.0,46.0,164,5.0,15.0,99,world
2,3,Memories,Maroon 5,pop,2019,1969-12-31,91.0,32.0,76.0,-7.0,8.0,57.0,189,84.0,5.0,99,world
3,4,Circles,Post Malone,dfw rap,2019,1969-12-31,120.0,76.0,70.0,-3.0,9.0,55.0,215,19.0,4.0,99,world
4,5,All I Want for Christmas Is You,Mariah Carey,dance pop,1994,1969-12-31,150.0,63.0,34.0,-7.0,7.0,35.0,241,16.0,4.0,98,world
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Feelings,Lauv,pop,2019,1969-12-31,103.0,47.0,69.0,-7.0,10.0,25.0,190,9.0,4.0,73,malasya
996,997,Mimpi (feat. Alif),K-Clique,malaysian indie,2019,1969-12-31,150.0,73.0,83.0,-7.0,10.0,87.0,253,53.0,29.0,66,malasya
997,998,Cinta Luar Biasa,Andmesh,indonesian pop,2019,1969-12-31,136.0,23.0,58.0,-12.0,10.0,32.0,256,81.0,3.0,66,malasya
998,999,Haa Tepok,MeerFly,malaysian hip hop,2019,1969-12-31,87.0,50.0,85.0,-12.0,15.0,68.0,211,66.0,31.0,65,malasya
999,1000,Hanya Rindu,Andmesh,indonesian pop,2019,1969-12-31,179.0,16.0,28.0,-12.0,11.0,20.0,252,89.0,3.0,65,malasya

Untuk memastikan bahwa konteks kolom pertama tersebut benar adalah ID (unik untuk setiap lagu), maka kita bisa periksa apakah judul lagu yang sama memiliki ID yang sama. Sebagai contoh (dan agar penjelasan lebih intuitif) akan dianalisa ID dari lagu "Dance Monkey"

In [9]:
df.loc[df["title"]=="Dance Monkey"]

,ID,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,country
0,1,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,world
50,51,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,africa
100,101,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,argentina
150,151,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,australia
200,201,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,belgium
250,251,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,bolivia
300,301,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,brazil
350,351,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,canada
400,401,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,germany
450,451,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,colombia
500,501,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,chile
550,551,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,spain
650,651,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,france
750,751,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,indonesia
800,801,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,israel
850,851,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,italy
950,951,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,malasya

Dari hasil di atas terlihat bahwa lagu yang sama, yaitu "Dance Monkey" ciptaan Tones and I, memiliki ID yang berbeda-beda, padahal secara intuitif ID lagu seharusnya unik untuk setiap lagu yang unik (berbeda), bukan untuk setiap entri yang berbeda. Oleh karena itu, dirasa kolom ID ini kurang cocok untuk konteks ID, lebih baik dinamakan kolom "nomor". Tetapi, mengingat bahwa dataframe sudah memiliki indeks, sebenarnya kolom "nomor" tidak diperlukan (redundant).

Dari pemaparan di atas, bisa disimpulkan bahwa kolom ID bisa dihapus karena tidak diperlukan.

In [10]:
df = df.drop("ID", axis=1)

## PEMERIKSAAN DATA DUPLIKAT

Selanjutnya, kita mencari entri data yang benar-benar duplikat, benar-benar duplikat dalam konteks dataset ini adalah bahwa **SELURUH** atribut pada satu lagu atau entri benar-benar sama **PERSIS**. Mengapa demikian? Karena bila duplikat didefinisikan sebagai entri atau lagu yang memiliki **SALAH SATU** atribut yang sama, maka lagu atau entri yang memiliki judul yang sama tetapi popular di negara berbeda akan terhitung sebagai duplikat, padahal mereka mendeskripsikan ketenaran lagu pada negara yang berbeda.

Maka untuk memeriksa kegandaan atau duplikat yang **SELURUH** atributnya sama persis, bisa dilakukan dengan proses di bawah

In [11]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [12]:
df[df.duplicated()]

Empty DataFrame
Columns: [title, artist, top genre, year, added, bpm, nrgy, dnce, dB, live, val, dur, acous, spch, pop, country]
Index: []

Terlihat dari program di atas bahwa setiap entri adalah **UNIK**, tidak ada entri yang benar-benar duplikat. Sehingga, bisa dilanjutkan ke tahap cleaning selanjutnya, yaitu pemeriksaan nilai null atau NA.

## PEMERIKSAAN NILAI NULL

In [13]:
df.loc[df.isnull().any(axis=1)]

,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,country
29,Do They Know It's Christmas? - 1984 Version,Band Aid,NaN,2004,1969-12-31,115.0,64.0,60.0,-7.0,10.0,35.0,223,16.0,4.0,87,world
72,Do They Know It's Christmas? - 1984 Version,Band Aid,NaN,2004,1969-12-31,115.0,64.0,60.0,-7.0,10.0,35.0,223,16.0,4.0,87,africa
96,Fire,DJ Big Sky,NaN,2019,1969-12-31,114.0,56.0,65.0,-7.0,5.0,64.0,463,2.0,21.0,47,africa
136,Ya No Mas,Fer Palacio,NaN,2019,1969-12-31,100.0,68.0,80.0,-6.0,7.0,88.0,158,14.0,6.0,75,argentina
170,Do They Know It's Christmas? - 1984 Version,Band Aid,NaN,2004,1969-12-31,115.0,64.0,60.0,-7.0,10.0,35.0,223,16.0,4.0,87,australia
228,Do They Know It's Christmas? - 1984 Version,Band Aid,NaN,2004,1969-12-31,115.0,64.0,60.0,-7.0,10.0,35.0,223,16.0,4.0,87,belgium
290,Loco,Beéle,NaN,2019,1969-12-31,105.0,56.0,82.0,-6.0,5.0,77.0,204,16.0,17.0,82,bolivia
370,Do They Know It's Christmas? - 1984 Version,Band Aid,NaN,2004,1969-12-31,115.0,64.0,60.0,-7.0,10.0,35.0,223,16.0,4.0,87,canada
416,Do They Know It's Christmas? - 1984 Version,Band Aid,NaN,2004,1969-12-31,115.0,64.0,60.0,-7.0,10.0,35.0,223,16.0,4.0,87,germany
433,Wonderful Dream (Holidays Are Coming) - Radio ...,Melanie Thornton,NaN,2001,1969-12-31,150.0,68.0,58.0,-5.0,26.0,52.0,232,11.0,3.0,79,germany
477,Loco,Beéle,NaN,2019,1969-12-31,105.0,56.0,82.0,-6.0,5.0,77.0,204,16.0,17.0,82,colombia
623,Do They Know It's Christmas? - 1984 Version,Band Aid,NaN,2004,1969-12-31,115.0,64.0,60.0,-7.0,10.0,35.0,223,16.0,4.0,87,usa
749,"Lamborghini (From ""Jai Mummy Di"")",Meet Bros.,desi pop,2019,1969-12-31,NaN,NaN,NaN,NaN,NaN,NaN,247,NaN,NaN,48,india
770,Halu,Feby Putri,NaN,2019,1969-12-31,116.0,25.0,34.0,-15.0,11.0,10.0,266,87.0,4.0,79,indonesia
790,Kartonyono Medot Janji,Denny Caknan,NaN,2019,1969-12-31,130.0,78.0,73.0,-6.0,21.0,75.0,262,31.0,3.0,71,indonesia
791,Percaya Aku,Chintya Gabriella,NaN,2019,1969-12-31,140.0,49.0,54.0,-8.0,20.0,30.0,232,74.0,3.0,71,indonesia

Melihat dari hasil di atas, kolom dengan nilai kosong paling banyak adalah kolom "top genre", dengan 15 nilai kosong dan entri dengan atribut kosong paling banyak adalah entri pada index 749, dengan 8 nilai kosong.

Ada 2 opsi untuk mengatasi nilai kosong:
1. Menghapus entri/kolom yang memiliki nilai kosong
2. Mengisi nilai kosong tersebut dengan suatu nilai lain (imputing)

Untuk nilai kosong pada entri dengan index 749 lebih masuk akal dilakukan penghapusan, karena data yang dimiliki sangat banyak (1000 entri) dan menghapus satu entri untuk negara India tidak akan terlalu memengaruhi analisis.

Sedangkan untuk nilai kosong pada kolom "top genre" lebih masuk akal dilakukan pengisian karena dataset hanya memiliki 2 kolom atribut kategorikal, sehingga penghapusan kolom "top genre" akan mempersulit analisis karena kekurangan atribut kategorikal.

Penanganan akan dimulai dengan nilai kosong pada entri index 749, tentukan terlebih dahulu urutan entri (lagu) tersebut pada urutan popularitas di negara India.

In [14]:
df_India = df.loc[df["country"]=="india"]
df_India.sort_values("pop", ascending=0)

,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,country
700,Memories,Maroon 5,pop,2019,1969-12-31,91.0,32.0,76.0,-7.0,8.0,57.0,189,84.0,5.0,99,india
701,ROXANNE,Arizona Zervas,pop rap,2019,1969-12-31,117.0,60.0,62.0,-6.0,46.0,46.0,164,5.0,15.0,99,india
702,Circles,Post Malone,dfw rap,2019,1969-12-31,120.0,76.0,70.0,-3.0,9.0,55.0,215,19.0,4.0,99,india
703,Falling,Trevor Daniel,alternative r&b,2018,1969-12-31,127.0,43.0,78.0,-9.0,9.0,24.0,159,12.0,4.0,97,india
704,Blinding Lights,The Weeknd,canadian contemporary r&b,2019,1969-12-31,171.0,80.0,51.0,-4.0,9.0,35.0,202,0.0,6.0,96,india
705,bad guy,Billie Eilish,electropop,2019,1969-12-31,135.0,43.0,70.0,-11.0,10.0,56.0,194,33.0,38.0,96,india
706,hot girl bummer,blackbear,pop,2019,1969-12-31,130.0,56.0,78.0,-7.0,40.0,68.0,185,13.0,8.0,96,india
707,Heartless,The Weeknd,canadian contemporary r&b,2019,1969-12-31,170.0,75.0,53.0,-6.0,12.0,20.0,200,1.0,11.0,94,india
708,Trampoline (with ZAYN),SHAED,electropop,2019,1969-12-31,127.0,46.0,62.0,-6.0,14.0,50.0,184,56.0,3.0,92,india
709,My Oh My (feat. DaBaby),Camila Cabello,dance pop,2019,1969-12-31,105.0,49.0,72.0,-6.0,9.0,38.0,171,2.0,3.0,91,india
710,Señorita,Shawn Mendes,canadian pop,2019,1969-12-31,117.0,55.0,76.0,-6.0,8.0,75.0,191,4.0,3.0,89,india
711,Believer,Imagine Dragons,modern rock,2017,1969-12-31,125.0,78.0,78.0,-4.0,8.0,67.0,204,6.0,13.0,89,india
712,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,2019,1969-12-31,90.0,52.0,76.0,-4.0,7.0,93.0,158,53.0,6.0,88,india
713,On My Way,Alan Walker,electro house,2019,1969-12-31,170.0,69.0,51.0,-5.0,30.0,30.0,194,2.0,10.0,84,india
714,"Ghungroo (From ""War"")",Arijit Singh,desi pop,2019,1969-12-31,118.0,73.0,70.0,-6.0,53.0,86.0,303,7.0,3.0,75,india
715,"Tum Hi Aana (From ""Marjaavaan"")",Payal Dev,modern bollywood,2019,1969-12-31,90.0,40.0,47.0,-7.0,15.0,35.0,249,63.0,2.0,74,india
716,Filhall,B Praak,desi pop,2019,1969-12-31,80.0,66.0,53.0,-4.0,13.0,59.0,255,61.0,6.0,74,india
717,Makhna,Tanishk Bagchi,desi pop,2019,1969-12-31,125.0,70.0,70.0,-8.0,16.0,43.0,183,17.0,4.0,73,india
718,Yaad Piya Ki Aane Lagi,Neha Kakkar,desi pop,2019,1969-12-31,108.0,83.0,86.0,-4.0,11.0,69.0,257,38.0,5.0,72,india
719,"Duniyaa (From ""Luka Chuppi"")",Akhil,desi pop,2019,1969-12-31,77.0,66.0,44.0,-6.0,13.0,52.0,223,70.0,4.0,71,india
720,"Pachtaoge (From ""Jaani Ve"")",Arijit Singh,desi pop,2019,1969-12-31,170.0,69.0,52.0,-4.0,12.0,48.0,227,62.0,3.0,71,india
721,"Tujhe Kitna Chahne Lage (From ""Kabir Singh"")",Arijit Singh,desi pop,2019,1969-12-31,70.0,40.0,43.0,-8.0,11.0,31.0,285,74.0,4.0,69,india
722,Pal Pal Dil Ke Paas- Title Track,Arijit Singh,desi pop,2019,1969-12-31,124.0,51.0,56.0,-7.0,6.0,39.0,255,59.0,3.0,69,india
723,Sakhiyaan,Maninder Buttar,desi pop,2018,1969-12-31,83.0,67.0,71.0,-6.0,20.0,36.0,179,30.0,4.0,69,india
724,Proper Patola,Badshah,desi hip hop,2018,1969-12-31,172.0,82.0,77.0,-6.0,32.0,49.0,179,49.0,9.0,69,india
729,Chal Bombay,DIVINE,desi hip hop,2019,1969-12-31,95.0,62.0,86.0,-7.0,12.0,51.0,174,4.0,32.0,68,india
732,Kalank (Title Track),Arijit Singh,desi pop,2019,1969-12-31,118.0,55.0,57.0,-8.0,9.0,44.0,311,52.0,4.0,68,india
731,Vaaste,Dhvani Bhanushali,desi pop,2019,1969-12-31,90.0,48.0,44.0,-6.0,10.0,32.0,196,45.0,4.0,68,india
730,Ik Tera,Maninder Buttar,desi pop,2019,1969-12-31,93.0,71.0,83.0,-5.0,11.0,49.0,161,10.0,7.0,68,india
725,"Bekhayali (From ""Kabir Singh"")",Sachet Tandon,desi pop,2019,1969-12-31,172.0,59.0,31.0,-5.0,32.0,35.0,372,45.0,4.0,68,india
728,"Jai Jai Shivshankar (From ""War"")",Vishal Dadlani,desi pop,2019,1969-12-31,129.0,90.0,83.0,-5.0,7.0,53.0,231,26.0,8.0,68,india
726,"Dheeme Dheeme (From ""Pati Patni Aur Woh"")",Tony Kakkar,desi pop,2019,1969-12-31,110.0,97.0,80.0,-2.0,35.0,69.0,177,15.0,4.0,68,india
727,8 Parche,Baani Sandhu,punjabi pop,2019,1969-12-31,174.0,86.0,65.0,-2.0,20.0,73.0,210,16.0,21.0,68,india
733,"Shaitan Ka Saala (From ""Housefull 4"")",Sohail Sen,desi pop,2019,1969-12-31,100.0,77.0,84.0,-5.0,37.0,34.0,147,28.0,19.0,67,india
734,"Naah Goriye (From ""Bala"")",B Praak,desi pop,2019,1969-12-31,100.0,77.0,82.0,-2.0,6.0,72.0,185,46.0,6.0,67,india
735,"Ek Toh Kum Zindagani (From ""Marjaavaan"")",Neha Kakkar,desi pop,2019,1969-12-31,128.0,97.0,67.0,-2.0,6.0,72.0,190,6.0,9.0,67,india
736,"Don't Be Shy Again (From ""Bala"")",Sachin-Jigar,desi pop,2019,1969-12-31,105.0,91.0,80.0,-4.0,31.0,91.0,164,10.0,6.0,65,india
739,Chandigarh Mein,Badshah,desi hip hop,2019,1969-12-31,100.0,87.0,81.0,-2.0,7.0,34.0,205,1.0,6.0,64,india
740,Dance Like,Harrdy Sandhu,desi pop,2019,1969-12-31,100.0,82.0,86.0,-3.0,30.0,54.0,172,38.0,10.0,64,india
738,"Tu Hi Yaar Mera (From ""Pati Patni Aur Woh"")",Rochak,desi pop,2019,1969-12-31,87.0,38.0,72.0,-8.0,13.0,48.0,201,59.0,6.0,64,india
737,"Mere Sohneya (From ""Kabir Singh"")",Sachet Tandon,desi pop,2019,1969-12-31,136.0,64.0,38.0,-6.0,22.0,65.0,193,56.0,4.0,64,india
741,Sauda Khara Khara,Diljit Dosanjh,desi pop,2019,1969-12-31,145.0,92.0,69.0,-3.0,11.0,88.0,211,9.0,6.0,63,india
742,"Kaise Hua (From ""Kabir Singh"")",Vishal Mishra,desi pop,2019,1969-12-31,138.0,46.0,39.0,-7.0,11.0,15.0,235,45.0,4.0,62,india
743,"Muqabla (From ""Street Dancer 3D"")",Yash Narvekar,desi pop,2019,1969-12-31,120.0,91.0,80.0,-3.0,39.0,54.0,176,2.0,9.0,61,india
744,Ve Maahi,Arijit Singh,desi pop,2019,1969-12-31,103.0,55.0,65.0,-7.0,22.0,29.0,224,41.0,3.0,61,india
745,"O Saki Saki (From ""Batla House"")",Neha Kakkar,desi pop,2019,1969-12-31,108.0,96.0,74.0,0.0,36.0,57.0,191,16.0,7.0,60,india
746,"Tera Ban Jaunga (From ""Kabir Singh"")",Akhil Sachdeva,desi pop,2019,1969-12-31,94.0,53.0,61.0,-6.0,13.0,40.0,236,82.0,2.0,59,india
747,"Mummy Nu Pasand (From ""Jai Mummy Di"")",Sunanda Sharma,desi pop,2019,1969-12-31,94.0,97.0,78.0,0.0,35.0,80.0,185,1.0,11.0,57,india
748,"Hauli Hauli (From ""De De Pyaar De"")",Garry Sandhu,bhangra,2019,1969-12-31,95.0,98.0,71.0,-3.0,34.0,57.0,209,2.0,8.0,56,india
749,"Lamborghini (From ""Jai Mummy Di"")",Meet Bros.,desi pop,2019,1969-12-31,NaN,NaN,NaN,NaN,NaN,NaN,247,NaN,NaN,48,india

dilihat dari output program di atas, entri dengan atribut NaN yang banyak adalah lagu dengan ranking terendah dari negara India. Jadi tidak ada urutan di bawah atau di atasnya yang akan terpengaruh bila dilakukan penghapusan. Melihat kasus ini, maka opsi penghapusan masuk akal untuk data ini. Penghapusan akan dilakukan di akhir, bersama dengan penghapusan data yang irelevan dengan analisis.

selanjutnya, untuk kolom "top genre", *imputing* akan menggunakan categorical impute pada dari modul sklearn_pandas, seperti berikut

In [15]:
cat_imputer = CategoricalImputer()
df["top genre"] = pd.Series(cat_imputer.fit_transform(df["top genre"]))
df["top genre"].isnull().sum()

0

sekarang bisa kita cek apakah masih ada data NaN pada kolom "top genre"

In [16]:
df.loc[df.isnull().any(axis=1)]

,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,country
749,"Lamborghini (From ""Jai Mummy Di"")",Meet Bros.,desi pop,2019,1969-12-31,NaN,NaN,NaN,NaN,NaN,NaN,247,NaN,NaN,48,india

Bisa dilihat, telah berhasil dilakukan imputing untuk menggantikan nilai-nilai NaN pada kolom "top genre"

## MENGHAPUS ENTRI DAN ATRIBUT YANG IRELEVAN

In [17]:
df

,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,country
0,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,world
1,ROXANNE,Arizona Zervas,pop rap,2019,1969-12-31,117.0,60.0,62.0,-6.0,46.0,46.0,164,5.0,15.0,99,world
2,Memories,Maroon 5,pop,2019,1969-12-31,91.0,32.0,76.0,-7.0,8.0,57.0,189,84.0,5.0,99,world
3,Circles,Post Malone,dfw rap,2019,1969-12-31,120.0,76.0,70.0,-3.0,9.0,55.0,215,19.0,4.0,99,world
4,All I Want for Christmas Is You,Mariah Carey,dance pop,1994,1969-12-31,150.0,63.0,34.0,-7.0,7.0,35.0,241,16.0,4.0,98,world
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Feelings,Lauv,pop,2019,1969-12-31,103.0,47.0,69.0,-7.0,10.0,25.0,190,9.0,4.0,73,malasya
996,Mimpi (feat. Alif),K-Clique,malaysian indie,2019,1969-12-31,150.0,73.0,83.0,-7.0,10.0,87.0,253,53.0,29.0,66,malasya
997,Cinta Luar Biasa,Andmesh,indonesian pop,2019,1969-12-31,136.0,23.0,58.0,-12.0,10.0,32.0,256,81.0,3.0,66,malasya
998,Haa Tepok,MeerFly,malaysian hip hop,2019,1969-12-31,87.0,50.0,85.0,-12.0,15.0,68.0,211,66.0,31.0,65,malasya
999,Hanya Rindu,Andmesh,indonesian pop,2019,1969-12-31,179.0,16.0,28.0,-12.0,11.0,20.0,252,89.0,3.0,65,malasya

Data yang dimiliki sekarang terdiri dari 1000 entri dan 16 kolom, kita bisa analisa kolom-kolom dan entri-entri yang bisa dihapus berdasarkan:
1. Untuk entri, bisa dihapus bila dirasa data yang dimiliki terlalu banyak dan analisisnya sendiri tidak memerlukan data sebanyak itu
2. Untuk kolom kuantitatif, kolom dengan varians (variance) data yang rendah tidak menambahkan *insight* yang signifikan terhadap analisis.
3. Untuk kolom kategorikal, kolom dengan kategori entri paling seragam tidak memberikan *insight* yang signifikan terhadap analisis.

untuk entri, analis merasa bahwa top 50 lagu untuk setiap negara terlalu banyak, diputuskan untuk diambil setengahnya saja, sehingga akan difilter hanya top 25 lagu tiap negara.

selanjutnya untuk kolom, perhitungan variance akan digunakan method var() untuk pandas dataframe. Sedangkan keseragaman kategorinya akan dilihat dari value_counts()

### Kalkulasi varians

Pertama akan dihitung varians dari kolom kuantitatif, kolom "year" dikecualikan dalam kalkulasi karena analis akan memerlukan kolom tersebut sebagai salah satu kolom berisi *time series*

In [18]:
variance_array = []
df_kuanti = df.iloc[:, 5:14]
for column in df_kuanti.columns.tolist():
  variance_array.append(df_kuanti[column].var())
variance_array

[961.3174838164819,
 363.46400508725156,
 257.0525013991948,
 10.506111321742585,
 322.4338587084078,
 484.01567098160285,
 2623.9184424424425,
 828.2184007654951,
 71.1025012988941]

In [19]:
np.mean(variance_array)

658.0032195357237

untuk melihat kolom mana yang perlu dihapus, akan digunakan rata-rata variansnya sebagai patokan. Kolom dengan varians di bawah rata-rata akan dihapus

In [20]:
index_kolom_gagal = []
for variance in variance_array:
  if variance < np.mean(variance_array):
    index_kolom_gagal.append(variance_array.index(variance))

nama_kolom_gagal = []
for i in range(len(df_kuanti.columns.tolist())):
  if i in index_kolom_gagal:
    nama_kolom_gagal.append(df_kuanti.columns.tolist()[i])

nama_kolom_gagal

['nrgy', 'dnce', 'dB', 'live', 'val', 'spch']

In [21]:
df = df.drop(nama_kolom_gagal, axis=1)
df

,title,artist,top genre,year,added,bpm,dur,acous,pop,country
0,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,209,69.0,100,world
1,ROXANNE,Arizona Zervas,pop rap,2019,1969-12-31,117.0,164,5.0,99,world
2,Memories,Maroon 5,pop,2019,1969-12-31,91.0,189,84.0,99,world
3,Circles,Post Malone,dfw rap,2019,1969-12-31,120.0,215,19.0,99,world
4,All I Want for Christmas Is You,Mariah Carey,dance pop,1994,1969-12-31,150.0,241,16.0,98,world
...,...,...,...,...,...,...,...,...,...,...
995,Feelings,Lauv,pop,2019,1969-12-31,103.0,190,9.0,73,malasya
996,Mimpi (feat. Alif),K-Clique,malaysian indie,2019,1969-12-31,150.0,253,53.0,66,malasya
997,Cinta Luar Biasa,Andmesh,indonesian pop,2019,1969-12-31,136.0,256,81.0,66,malasya
998,Haa Tepok,MeerFly,malaysian hip hop,2019,1969-12-31,87.0,211,66.0,65,malasya
999,Hanya Rindu,Andmesh,indonesian pop,2019,1969-12-31,179.0,252,89.0,65,malasya

### Memeriksa keseragaman

sebelum mengamati keseragaman entri dalam kolom kategorikal, perlu diperhatikan bahwa kolom "title", "artist", "top genre", dan "country" tidak bisa dihapus karena merupakan atribut esensial yang bersangkutan dengan konteks dan esensi dataset. Sehingga yang bisa diperiksa hanya kolom "added"

In [22]:
df["added"].value_counts()

1969-12-31    1000
Name: added, dtype: int64

dari program di atas terlihat bahwa data di kolom "added" hanya memiliki 1 nilai yang seragam, data seperti ini tidak memberikan nilai pada analisis yang akan dilakukan, sehingga lebih baik kita buang (drop) saja kolomnya.

In [23]:
df = df.drop("added", axis=1)
df

,title,artist,top genre,year,bpm,dur,acous,pop,country
0,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,world
1,ROXANNE,Arizona Zervas,pop rap,2019,117.0,164,5.0,99,world
2,Memories,Maroon 5,pop,2019,91.0,189,84.0,99,world
3,Circles,Post Malone,dfw rap,2019,120.0,215,19.0,99,world
4,All I Want for Christmas Is You,Mariah Carey,dance pop,1994,150.0,241,16.0,98,world
...,...,...,...,...,...,...,...,...,...
995,Feelings,Lauv,pop,2019,103.0,190,9.0,73,malasya
996,Mimpi (feat. Alif),K-Clique,malaysian indie,2019,150.0,253,53.0,66,malasya
997,Cinta Luar Biasa,Andmesh,indonesian pop,2019,136.0,256,81.0,66,malasya
998,Haa Tepok,MeerFly,malaysian hip hop,2019,87.0,211,66.0,65,malasya
999,Hanya Rindu,Andmesh,indonesian pop,2019,179.0,252,89.0,65,malasya

### Seleksi top 25 tiap negara

untuk melakukan seleksi terhadap top 25 lagu di tiap negara, bisa digunakan group by dan head

In [24]:
df = df.groupby('country').head(25).sort_values("pop")
df

,title,artist,top genre,year,bpm,dur,acous,pop,country
824,<U+05DC><U+05E9><U+05D5><U+05D1> <U+05D4><U+05...,Ishay Ribo,israeli pop,2018,104.0,197,51.0,57,israel
823,<U+05D0><U+05DC><U+05D5><U+05E3> <U+05D4><U+05...,Hanan Ben Ari,israeli pop,2019,128.0,216,75.0,58,israel
822,<U+05E0><U+05D7><U+05DB><U+05D4> <U+05DC><U+05DA>,Nathan Goshen,israeli pop,2019,75.0,207,49.0,58,israel
821,<U+05DE><U+05E1><U+05E2>,Eliad,israeli pop,2019,115.0,207,12.0,59,israel
922,366<U+65E5>,HY,j-pop,2008,152.0,353,68.0,66,japan
...,...,...,...,...,...,...,...,...,...
200,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,belgium
750,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,indonesia
950,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,malasya
850,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,italy
0,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,world

Setelah melakukan seleksi top 25 di atas, terlihat bahwa ada beberapa judul lagu dalam dataset yang isinya bukan karakter normal yang bisa dibaca. Maka perlu dilakukan filter terhadap judul-judul seperti itu.

In [25]:
df[df.title.str.startswith('<')]

,title,artist,top genre,year,bpm,dur,acous,pop,country
824,<U+05DC><U+05E9><U+05D5><U+05D1> <U+05D4><U+05...,Ishay Ribo,israeli pop,2018,104.0,197,51.0,57,israel
823,<U+05D0><U+05DC><U+05D5><U+05E3> <U+05D4><U+05...,Hanan Ben Ari,israeli pop,2019,128.0,216,75.0,58,israel
822,<U+05E0><U+05D7><U+05DB><U+05D4> <U+05DC><U+05DA>,Nathan Goshen,israeli pop,2019,75.0,207,49.0,58,israel
821,<U+05DE><U+05E1><U+05E2>,Eliad,israeli pop,2019,115.0,207,12.0,59,israel
924,<U+7A7A><U+306E><U+9752><U+3055><U+3092><U+77E...,Aimyon,j-acoustic,2019,108.0,305,18.0,66,japan
923,<U+30C8><U+30EA><U+30B3>,Nissy,j-pop,2019,90.0,232,9.0,66,japan
920,<U+70B9><U+63CF><U+306E><U+5504>,Mrs. GREEN APPLE,anime rock,2018,152.0,307,45.0,67,japan
919,<U+30EF><U+30BF><U+30EA><U+30C9><U+30EA>,[ALEXANDROS],anime rock,2015,135.0,249,0.0,67,japan
918,<U+30CF><U+30EB><U+30CE><U+30D2>,Aimyon,j-acoustic,2019,107.0,327,26.0,67,japan
915,<U+30CF><U+30C3><U+30D4><U+30FC><U+30A8><U+30F...,back number,j-pop,2016,78.0,314,5.0,68,japan
916,<U+6253><U+4E0A><U+82B1><U+706B>,DAOKO×<U+7C73><U+6D25><U+7384><U+5E2B>,j-pop,2017,96.0,290,29.0,68,japan
911,<U+9AD8><U+5DBA><U+306E><U+82B1><U+5B50><U+305...,back number,j-pop,2014,138.0,295,7.0,69,japan
912,<U+541B><U+306F><U+30ED><U+30C3><U+30AF><U+309...,Aimyon,j-acoustic,2017,100.0,246,0.0,69,japan
913,<U+305F><U+3060><U+541B><U+306B><U+6674><U+308C>,Yorushika,j-pop,2018,140.0,199,34.0,69,japan
910,<U+30AF><U+30EA><U+30B9><U+30DE><U+30B9><U+30B...,back number,j-pop,2015,154.0,340,13.0,70,japan
908,<U+30CE><U+30FC><U+30C0><U+30A6><U+30C8>,Official HIGE DANdism,anime rock,2018,150.0,202,6.0,72,japan

Terlihat pada program di atas, lagu-lagu dengan judul karakter tak dapat dibaca mayoritas dari negara Israel dan Jepang, karena mereka menggunakan karakter-karakter yang berbeda dari karakter latin biasa. Secara logika, cara paling mudah adalah melakukan penghapusan data-data dari negara Jepang dan Israel, tetapi sebelum hal tersebut bisa dilakukan, harus dipastikan bahwa ada cukup banyak data negara bila kedua negara tersebut dihapus.

In [26]:
df["country"].value_counts().size

20

Terlihat total ada 20 data negara yang berbeda, menghapus 2 dari 20 tidak akan berdampak terlalu besar terhadap analisi. Oleh karena itu, untuk menghindari judul dengan karakter yang tidak bisa dibaca, semua data lagu dari kedua negara tersebut akan dihapus.

In [27]:
df = df.loc[(df["country"] != "japan") & (df["country"] != "israel")]
df

,title,artist,top genre,year,bpm,dur,acous,pop,country
722,Pal Pal Dil Ke Paas- Title Track,Arijit Singh,desi pop,2019,124.0,255,59.0,69,india
723,Sakhiyaan,Maninder Buttar,desi pop,2018,83.0,179,30.0,69,india
724,Proper Patola,Badshah,desi hip hop,2018,172.0,179,49.0,69,india
721,"Tujhe Kitna Chahne Lage (From ""Kabir Singh"")",Arijit Singh,desi pop,2019,70.0,285,74.0,69,india
720,"Pachtaoge (From ""Jaani Ve"")",Arijit Singh,desi pop,2019,170.0,227,62.0,71,india
...,...,...,...,...,...,...,...,...,...
200,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,belgium
750,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,indonesia
950,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,malasya
850,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,italy
0,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,world

## STANDARDISASI KOLOM DAN ENTRI

Bila dilihat dari nama-nama kolom yang ada, nama-namanya kurang deskriptif. Agar analis dapat dengan lebih mudah mendapat *insight* dari dataset, ada baiknya nama kolom distandarisasi sesuai konteksnya.

In [28]:
df.rename(columns = {"dur" : "duration",
                     "acous": "acousticness",
                     "pop": "popularity"}, inplace=True)
df

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,title,artist,top genre,year,bpm,duration,acousticness,popularity,country
722,Pal Pal Dil Ke Paas- Title Track,Arijit Singh,desi pop,2019,124.0,255,59.0,69,india
723,Sakhiyaan,Maninder Buttar,desi pop,2018,83.0,179,30.0,69,india
724,Proper Patola,Badshah,desi hip hop,2018,172.0,179,49.0,69,india
721,"Tujhe Kitna Chahne Lage (From ""Kabir Singh"")",Arijit Singh,desi pop,2019,70.0,285,74.0,69,india
720,"Pachtaoge (From ""Jaani Ve"")",Arijit Singh,desi pop,2019,170.0,227,62.0,71,india
...,...,...,...,...,...,...,...,...,...
200,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,belgium
750,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,indonesia
950,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,malasya
850,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,italy
0,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,world

Selanjutnya, dalam kolom country ada beberapa nama negara yang salah (typo) sehingga harus distandarisasi.

In [29]:
df["country"].value_counts()

india        25
france       25
world        25
bolivia      25
belgium      25
argentina    25
australia    25
africa       25
canada       25
usa          25
colombia     25
chile        25
spain        25
germany      25
italy        25
brazil       25
indonesia    25
malasya      25
Name: country, dtype: int64

Terlihat dari output di atas, negara "malaysia" ditulis sebagai "malasya". Ini perlu diperbaiki

In [31]:
df.loc[df["country"]=="malasya", "country"] = "malaysia"
df["country"].value_counts()

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

india        25
france       25
world        25
bolivia      25
belgium      25
argentina    25
australia    25
africa       25
canada       25
usa          25
colombia     25
chile        25
spain        25
germany      25
italy        25
brazil       25
indonesia    25
malaysia     25
Name: country, dtype: int64

# FINALISASI

Dataset yang dimiliki sekarang sudah "bersih" dan sesuai dengan keperluan serta tujuan analis, maka saatnya dataset yang baru ini kita finalisasi sebagai file csv baru.

In [32]:
df

,title,artist,top genre,year,bpm,duration,acousticness,popularity,country
722,Pal Pal Dil Ke Paas- Title Track,Arijit Singh,desi pop,2019,124.0,255,59.0,69,india
723,Sakhiyaan,Maninder Buttar,desi pop,2018,83.0,179,30.0,69,india
724,Proper Patola,Badshah,desi hip hop,2018,172.0,179,49.0,69,india
721,"Tujhe Kitna Chahne Lage (From ""Kabir Singh"")",Arijit Singh,desi pop,2019,70.0,285,74.0,69,india
720,"Pachtaoge (From ""Jaani Ve"")",Arijit Singh,desi pop,2019,170.0,227,62.0,71,india
...,...,...,...,...,...,...,...,...,...
200,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,belgium
750,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,indonesia
950,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,malaysia
850,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,italy
0,Dance Monkey,Tones and I,australian pop,2019,98.0,209,69.0,100,world

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 450 entries, 722 to 0
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         450 non-null    object
 1   artist        450 non-null    object
 2   top genre     450 non-null    object
 3   year          450 non-null    int64
 4   bpm           450 non-null    float64
 5   duration      450 non-null    int64
 6   acousticness  450 non-null    float64
 7   popularity    450 non-null    int64
 8   country       450 non-null    object
dtypes: float64(2), int64(3), object(4)
memory usage: 35.2+ KB

In [35]:
df.describe()

              year         bpm    duration  acousticness  popularity
count   450.000000  450.000000  450.000000    450.000000  450.000000
mean   2008.735556  124.771111  197.417778     34.808889   90.497778
std      18.787852   32.808801   41.639118     30.561106    6.054411
min    1942.000000   67.000000  117.000000      0.000000   69.000000
25%    2010.000000   96.000000  166.500000      7.000000   88.000000
50%    2019.000000  120.000000  196.000000     22.000000   91.000000
75%    2019.000000  150.000000  222.000000     61.000000   95.000000
max    2019.000000  202.000000  328.000000     96.000000  100.000000

In [36]:
df.to_csv("top25country.csv")

# DAFTAR REFERENSI

Referensi yang digunakan untuk melakukan pembersihan dan prapemrosesan data ini antara lain,
1. [pandas.DataFrame.replace](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html)
2. [How to filter rows in pandas by regex](https://stackoverflow.com/questions/15325182/how-to-filter-rows-in-pandas-by-regex)
3. [Select rows from a Pandas DataFrame based on values in a column](https://www.interviewqs.com/ddi-code-snippets/rows-cols-python)
4. [Pandas Groupby – Sort within groups](https://www.geeksforgeeks.org/pandas-groupby-sort-within-groups/)
5. [How to drop one or multiple columns in Pandas Dataframe](https://www.geeksforgeeks.org/how-to-drop-one-or-multiple-columns-in-pandas-dataframe/)
6. [Pandas – Filling NaN in Categorical data](https://www.geeksforgeeks.org/pandas-filling-nan-in-categorical-data/)
7. [error UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte](https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in)
8. [What can be used to evaluate "variance" of samples of categorical data?](https://stats.stackexchange.com/questions/354133/what-can-be-used-to-evaluate-variance-of-samples-of-categorical-data)